const activities = [
  {
    name: "Red Rocks Amphitheatre",
    trail: "Red Rocks Trail",
    type: "Hiking",
    location: { lat: 39.6654, lng: -105.2057 },
    difficulty: "Easy",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Garden of the Gods",
    trail: "Garden Trail",
    type: "Hiking",
    location: { lat: 38.8784, lng: -104.8694 },
    difficulty: "Medium",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Chautauqua Park",
    trail: "Chautauqua Trail",
    type: "Hiking",
    location: { lat: 40.0005, lng: -105.2817 },
    difficulty: "Easy",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Rocky Mountain NP",
    trail: "Emerald Lake Trail",
    type: "Hiking",
    location: { lat: 40.3105, lng: -105.648 },
    difficulty: "Easy",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
  },
  {
    name: "Rocky Mountain NP",
    trail: "Sky Pond Trail",
    type: "Hiking",
    location: { lat: 40.3109, lng: -105.6627 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "Yes",
    camping: "Yes",
  },
  {
    name: "Manitou Springs",
    trail: "The Incline",
    type: "Hiking",
    location: { lat: 38.8577, lng: -104.9334 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Flatirons",
    trail: "Flatirons Loop Trail",
    type: "Hiking",
    location: { lat: 39.9999, lng: -105.2834 },
    difficulty: "Medium",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Boulder",
    trail: "Bear Peak Trail",
    type: "Hiking",
    location: { lat: 39.9787, lng: -105.2954 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Eldorado Canyon",
    trail: "Rattlesnake Gulch Trail",
    type: "Hiking",
    location: { lat: 39.9332, lng: -105.2933 },
    difficulty: "Medium",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "No",
  },
  {
    name: "Glenwood Canyon",
    trail: "Hanging Lake Trail",
    type: "Hiking",
    location: { lat: 39.5981, lng: -107.1917 },
    difficulty: "Medium",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "Yes",
    camping: "No",
  },
  {
    name: "Mount Evans Wilderness",
    trail: "Mount Bierstadt Trail",
    type: "Hiking",
    location: { lat: 39.582, lng: -105.6438 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "Yes",
    camping: "Yes",
  },
  {
    name: "Maroon Bells",
    trail: "Maroon Bells Scenic Loop Trail",
    type: "Hiking",
    location: { lat: 39.0986, lng: -106.9414 },
    difficulty: "Easy",
    elevationGain: "160 ft",
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
  },
  {
    name: "Rocky Mountain NP",
    trail: "Bear Lake Loop",
    type: "Hiking",
    location: { lat: 40.31196, lng: -105.64581 },
    difficulty: "Beginner",
    elevationGain: "45 ft",
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
  },
  {
    name: "Maroon Bells",
    trail: "Maroon Lake Scenic Loop Trail",
    type: "Hiking",
    location: { lat: 39.09991, lng: -106.94192 },
    difficulty: "Beginner",
    elevationGain: "160 ft",
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
  },
  {
    name: "Bangor City Forest",
    trail: "East-West and Deer Trail Loop",
    type: "Hiking",
    location: { lat: 29.951722, lng: -95.237709 },
    difficulty: "Beginner",
    elevationGain: "39 ft",
    entrancePass: "No",
    gearNeeded: "No",
    camping: "Yes",
  },
];

module.exports = activities;
