const activities = [
  {
    id: "1",
    name: "Red Rocks Amphitheatre",
    type: "hiking",
    difficulty: "easy",
    location: { lat: 39.6654, lng: -105.2057 },
    durationHours: 2,
  },
  {
    id: "2",
    name: "Garden of the Gods",
    type: "hiking",
    difficulty: "medium",
    location: { lat: 38.8784, lng: -104.8694 },
    durationHours: 3,
  },
  {
    id: "3",
    name: "Chautauqua Trail",
    type: "hiking",
    difficulty: "easy",
    location: { lat: 40.0005, lng: -105.2817 },
    durationHours: 1.5,
  },
  {
    id: "4",
    name: "Emerald Lake Trail",
    type: "hiking",
    difficulty: "easy",
    location: { lat: 40.3105, lng: -105.648 },
    durationHours: 2,
  },
  {
    id: "5",
    name: "Sky Pond Trail",
    type: "hiking",
    difficulty: "hard",
    location: { lat: 40.3109, lng: -105.6627 },
    durationHours: 4.5,
  },
  {
    id: "6",
    name: "The Incline at Manitou Springs",
    type: "hiking",
    difficulty: "hard",
    location: { lat: 38.8577, lng: -104.9334 },
    durationHours: 2,
  },
  {
    id: "7",
    name: "Flatirons Loop Trail",
    type: "hiking",
    difficulty: "medium",
    location: { lat: 39.9999, lng: -105.2834 },
    durationHours: 2.5,
  },
  {
    id: "8",
    name: "Bear Peak Trail",
    type: "hiking",
    difficulty: "hard",
    location: { lat: 39.9787, lng: -105.2954 },
    durationHours: 4,
  },
  {
    id: "9",
    name: "Rattlesnake Gulch Trail",
    type: "hiking",
    difficulty: "medium",
    location: { lat: 39.9332, lng: -105.2933 },
    durationHours: 2.5,
  },
  {
    id: "10",
    name: "Hanging Lake Trail",
    type: "hiking",
    difficulty: "medium",
    location: { lat: 39.5981, lng: -107.1917 },
    durationHours: 3,
  },
  {
    id: "11",
    name: "Mount Bierstadt Trail",
    type: "hiking",
    difficulty: "hard",
    location: { lat: 39.582, lng: -105.6438 },
    durationHours: 5,
  },
  {
    id: "12",
    name: "Maroon Bells Scenic Loop Trail",
    type: "hiking",
    difficulty: "easy",
    location: { lat: 39.0986, lng: -106.9414 },
    durationHours: 1.5,
  },
];

module.exports = activities;
